title: Phong Tran
description: Personal tech blog about JavaScript intergrated.
author: Phong Tran
github: https://github.com/bodetaima
about: I'm a front-end engineer. Mainly adopted vanilla JavaScript, NodeJS along with front-end library like React, Vue,...
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: ["javascript", "nodejs", "reactjs", "vuejs", "frontend"]

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/phongisntreal"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/phong-trung-tran-09285a194/"
    - icon: fa-github
      link: "https://github.com/bodetaima"

urls:
    - text: Resume
      url: /resume/
    - text: My Projects
      url: /projects/

url: "https://bodetaima.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
